// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt_v0._04.DbContexts;

#nullable disable

namespace Projekt_v0._04.Migrations
{
    [DbContext(typeof(ProjektDbContext))]
    [Migration("20220611183217_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Projekt_v0._04.DTOs.LoginDTO", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("loginPassword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("loginUsername")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("Projekt_v0._04.DTOs.ReservationDTO", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataPrzyjazdu")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataWyjazdu")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Hotel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Miasto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumerPokoju")
                        .HasColumnType("int");

                    b.Property<bool>("RezerwacjaPotwierdzona")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Użytkownik")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
